// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmkjgFbBx2XJpTz9CsxT-Zh0pvPuHrYrc',
    appId: '1:288572061243:web:92927ccc7dfdf6f4918e1e',
    messagingSenderId: '288572061243',
    projectId: 'wesafe-c1292',
    authDomain: 'wesafe-c1292.firebaseapp.com',
    storageBucket: 'wesafe-c1292.appspot.com',
    measurementId: 'G-LQ8FEMF5X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4sTROUZPP_Uy9g-gzXzbyqHHILeoDtbI',
    appId: '1:288572061243:android:46247b51ea6167f0918e1e',
    messagingSenderId: '288572061243',
    projectId: 'wesafe-c1292',
    storageBucket: 'wesafe-c1292.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA96ZxdcQGaO08Ffy9c_k5afkzjkbWOzbI',
    appId: '1:288572061243:ios:9b0289f427c0b7c4918e1e',
    messagingSenderId: '288572061243',
    projectId: 'wesafe-c1292',
    storageBucket: 'wesafe-c1292.appspot.com',
    iosClientId: '288572061243-2d6387cvh7r10roav76p82cecuqbl0hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.wesafeMainVersion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA96ZxdcQGaO08Ffy9c_k5afkzjkbWOzbI',
    appId: '1:288572061243:ios:9b0289f427c0b7c4918e1e',
    messagingSenderId: '288572061243',
    projectId: 'wesafe-c1292',
    storageBucket: 'wesafe-c1292.appspot.com',
    iosClientId: '288572061243-2d6387cvh7r10roav76p82cecuqbl0hk.apps.googleusercontent.com',
    iosBundleId: 'com.example.wesafeMainVersion',
  );
}
